name: Build Service

on:
  workflow_dispatch:
  pull_request:
    paths-ignore: ['*.md']
    branches: ['master', 'next']
  push:
    paths-ignore: ['*.md']
    branches: ['master', 'next']

jobs:
  BuildPackage:
    runs-on: ubuntu-latest
    steps:
      - uses: buildjet/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-jellyfin-${{ github.sha }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: |
          sudo snap install yq deno
          sudo apt-get install -y build-essential openssl libssl-dev libc6-dev clang libclang-dev ca-certificates
      - uses: actions/checkout@v3
      - id: packageManager
        if: steps.packageCache.outputs.cache-hit != 'true'
        run: |
          cd ~/ && git clone https://github.com/Start9Labs/start-os.git --branch sdk;
          cd start-os;
          git submodule update --init --recursive
          cd backend;
          export RUSTFLAGS="";
          export OS_ARCH=$(uname -m);
          ./install-sdk.sh;
      - run: |
          git submodule update --init --recursive
          start-sdk init
          make
          mv jellyfin*s9pk ~/
      - uses: actions/upload-artifact@v3
        with:
          name: jellyfin.s9pk
          path: ~/*.s9pk
          